### ISSUE TITLE
关于BotManagerConsole

### ISSUE THREAD

**Issue by kkacom** [Alex1911-Jiang/GreenOnions#1]
用Console的方式启动好像没法调用plainmessagehandler，而且好像也没生成config.json
我想部署到arm板子上使用，麻烦大佬指点一下QAQ

**Comment by Alex1911-Jiang** [comment]
没创建config.json是我的疏忽，你拿一下最新的release吧，这个版本创建了
我试了一下是有进入PlainMessageHandler的，就算没有config也会进，你确认一下Mirai是否有收到这条消息，以及收普通消息是不会进到PlainMessageHandler的，在GroupMessage里面就被处理掉了，你试试发功能命令过去看看有没有进PlainMessageHandler，如果还是没有进，看看目录下有没有生成一个error.log文件，有的话把异常信息给我看看
至于arm，抱歉，我没有arm的设备...

**Comment by kkacom** [comment]
好的好的，我先跑一下看看，感谢大佬回复

**Comment by kkacom** [comment]
来回复一下调试结果，在板子上搭了dotnet环境之后把代码重新编译一下就能跑起来了。
不过有个比较麻烦的问题，windows上的目录分级符是\，linux上是/，所以所有关于目录访问或者生成的功能都会出问题，如果有要进行类似的移植需要手动改写这部分代码。
另外用console启动的时候好像不会读取config，不知道是不是前面提到的目录层级问题？

**Comment by Alex1911-Jiang** [comment]
原来还有这种问题吗, 谢谢大佬指点
我改了路径拼接方式, 你试试v1.0c版本行不行呗

**Comment by kkacom** [comment]
好的现在完美解决了，大佬牛逼（大拇指
