### ISSUE TITLE
添加一个涩图标签屏蔽选项

### ISSUE THREAD

**Issue by modeilan** [Alex1911-Jiang/GreenOnions#10]
有些标签的涩图不想看到，添加个选项屏蔽掉

**Comment by Alex1911-Jiang** [comment]
屏蔽是指忽略带有这个标签的命令还是不带标签的命令过滤掉出现某些标签的图?
如果是第二种的话你应该去api.lolicon.app那里提, 机器人没法在请求api前得知作品拥有的标签, 如果请求回来之后发现有标签再重新请求会浪费很多时间

**Comment by Alex1911-Jiang** [comment]
算是加了个关键词屏蔽，含有屏蔽词的命令会被直接忽略，可以下新版试试
