### ISSUE TITLE
Armbian系统下不会读取config.json

### ISSUE THREAD

**Issue by Young-Ginger** [Alex1911-Jiang/GreenOnions#13]
armbian的环境下每次启动都会覆盖重新生成config.json，而且连接了以后关闭也不会保存config.json

**Comment by Alex1911-Jiang** [comment]
看看有没有Error.log，有的话看看里面有什么内容
我这没有arm的硬件调试，能不能ssh让我远程看看？

**Comment by Young-Ginger** [comment]
没有Error.log，设备是本地的，我去做个DDNS

**Comment by Alex1911-Jiang** [comment]
不用了， 我找到问题了，我改一下🤡

**Comment by Alex1911-Jiang** [comment]
更新了，还是要先删除一次config，或者手动改一下配置文件里的QQId为机器人的QQ号
之前的版本保存了个0，0的时候总是会重置配置文件，不为0就可以读了

**Comment by Young-Ginger** [comment]
好像没有用，启动了config还是会变成默认

**Comment by Young-Ginger** [comment]
只要我启动 配置文件就重置了
