### ISSUE TITLE
[Bug] RSS的消息内容、第三方谷歌翻译API处理原文  遇到某些特殊符号有问题

### ISSUE THREAD

**Issue by kafovin** [Alex1911-Jiang/GreenOnions#15]
1. RSS消息内容的某些特殊符号未解码。
    例如，直接显示为`&#39;`的部分本应显示为解码后对应的`'`。

    + 原因：没有解码RSS的消息内容中被HTML编码的特殊符号。

<br/>

2. 第三方谷歌翻译API遇到原文含某些特殊符号得不到翻译结果。
    例如，原文文本包括`&`导致该字符以后的部分被抛弃。

    + 原因：在API的翻译请求中，没有URI编码原文文本。

<br/>

实例：

![image](https://www.linkpicture.com/q/4930_1.png)

**Comment by Alex1911-Jiang** [comment]
改了改了，过两天跟别的一起发布Release🤡
