### ISSUE TITLE
Linux 缺少 BotManagerConsole.dll 或者说 新版更改了启动连接方式？

### ISSUE THREAD

**Issue by 1301715759** [Alex1911-Jiang/GreenOnions#19]
![image](https://user-images.githubusercontent.com/44659174/214547804-7d2b556d-d28d-4ac1-a295-7d8c244b6105.png)
debian 10系统中运行，没有BotManagerConsole.dll了
直接 dotnet  GreenOnions.BotMain.dll 应该不对（
![image](https://user-images.githubusercontent.com/44659174/214548113-0a574d05-8894-4e63-b045-3ae175722a10.png)

**Comment by 1301715759** [comment]
新版本包的文件
![image](https://user-images.githubusercontent.com/44659174/214549615-02950531-bd51-4d2a-93e2-d060ca4f28cb.png)
上一个版本
![image](https://user-images.githubusercontent.com/44659174/214549681-03e64d0b-908b-4351-8262-fcf4ea996acd.png)
很明显少加了东西

**Comment by Alex1911-Jiang** [comment]
抱歉，是我小丑了，没打包到，一会我更新一下Release🤡

**Comment by Alex1911-Jiang** [comment]
压缩包替换了
