### ISSUE TITLE
设置恢复默认值功能

### ISSUE THREAD

**Issue by KJH-x** [Alex1911-Jiang/GreenOnions#20]
现在调整部分设置后不如预期想调回去不太方便，要是每个输入框能安排个充值按钮就太棒了

**Comment by Alex1911-Jiang** [comment]
工作量太大，按钮不会加的，而且排版也要重新设计，你想还原直接删掉配置文件就好了。
只还原某个值的话我可以加个命令还原某个值，从QQ上发消息给机器人指定属性还原

**Comment by Alex1911-Jiang** [comment]
新版已经加上重置的命令了，格式是：“葱葱命令 --reset <属性名>” 可以用界面上显示的中文属性名字，也可以用配置文件里的英文变量名。
