### ISSUE TITLE
【功能请求】一些功能请求与建议

### ISSUE THREAD

**Issue by bf179** [Alex1911-Jiang/GreenOnions#22]
- 能否支持百度云鉴黄，腾讯云的后付费日结貌似只能万条万条的买？隔壁百度云貌似更划算一些
- 是否会考虑添加搜本子的功能，主要是哔咔
- 添加[animetrace](https://ai.animedb.cn/)识别动漫人物

**Comment by Alex1911-Jiang** [comment]
1.最早其实尝试过阿里云的鉴黄，但是它和腾讯的判定标准不一样，它觉得没问题的图在群里被举报还是封号，所以就没加上去，百度我估计也一样，如果你确定要，可以加。（顺便问问百度有免费额度用于调试吗？）
2.有具体API或者网站的话可以加，但现在我不知道怎么搜（哔咔是啥？）
3.这个可以，等有空了就加上。

**Comment by bf179** [comment]
> 1.最早其实尝试过阿里云的鉴黄，但是它和腾讯的判定标准不一样，它觉得没问题的图在群里被举报还是封号，所以就没加上去，百度我估计也一样，如果你确定要，可以加。（顺便问问百度有免费额度用于调试吗？） 2.有具体API或者网站的话可以加，但现在我不知道怎么搜（哔咔是啥？） 3.这个可以，等有空了就加上。
1.百度云我记得有免费额度来调试的，注册会有一万次免费额度，不过这个也不是太过于重要
2.哔咔就是一个本子站啊，我记得是有api的，不过这个倒也是可加可不加，毕竟感觉搜索和浏览不太好做
3.十分感谢

**Comment by bf179** [comment]
> > 1.最早其实尝试过阿里云的鉴黄，但是它和腾讯的判定标准不一样，它觉得没问题的图在群里被举报还是封号，所以就没加上去，百度我估计也一样，如果你确定要，可以加。（顺便问问百度有免费额度用于调试吗？） 2.有具体API或者网站的话可以加，但现在我不知道怎么搜（哔咔是啥？） 3.这个可以，等有空了就加上。
> > 1.百度云我记得有免费额度来调试的，注册会有一万次免费额度，不过这个也不是太过于重要
> > 2.哔咔就是一个本子站啊，我记得是有api的，不过这个倒也是可加可不加，毕竟感觉搜索和浏览不太好做
> > 3.十分感谢

我翻了一下，找不到之前看到的api文档了

**Comment by Alex1911-Jiang** [comment]
搜人物的插件做好了 Release: [2023.04.06](https://github.com/Alex1911-Jiang/GreenOnions.Plugins/releases/tag/2023.04.06)
说明在这: [GreenOnions.AnimeTrace](https://github.com/Alex1911-Jiang/GreenOnions.Plugins/tree/main/GreenOnions.AnimeTrace)

**Comment by bf179** [comment]
> 搜人物的插件做好了 Release: [2023.04.06](https://github.com/Alex1911-Jiang/GreenOnions.Plugins/releases/tag/2023.04.06) 说明在这: [GreenOnions.AnimeTrace](https://github.com/Alex1911-Jiang/GreenOnions.Plugins/tree/main/GreenOnions.AnimeTrace)

辛苦大佬
