### ISSUE TITLE
关于搜图功能的一点需求？（建议？想法？）

### ISSUE THREAD

**Issue by ghost** [Alex1911-Jiang/GreenOnions#4]
**1、把saucenao和Ascii2D的搜索结果合并在一条转发消息里，这样看起来美观一点点。**
![Screenshot_2022-05-25-19-29-59-02_9d26c6446fd7bb8](https://user-images.githubusercontent.com/83597535/170254742-ef55938e-cbcb-46a9-b652-62af013222a9.jpg)

**2、在用户发送图片后，机器人可以说一句“正在搜索，请稍后”。**

**3、Ascii2D的搜索结果显示前3条，因为有可能第二条或者第三条才是正确答案。**
![Cache_6f6aa17a6aae9e6f](https://user-images.githubusercontent.com/83597535/170255136-aa84bbc5-fa1d-4f90-bddd-22ac1f237365.jpg)
![image](https://user-images.githubusercontent.com/83597535/170254834-6c3d7153-687a-4c7b-ab63-cae20cc29933.png)

**Comment by Alex1911-Jiang** [comment]
行, 过几天改, 先铲完屎山

**Comment by Alex1911-Jiang** [comment]
这几个功能添加好了, 可以拿一下最新的Release试试
默认都没有启用, 需要设置一下
