### ISSUE TITLE
可以添加一个自己建的图库么

### ISSUE THREAD

**Issue by Wuyileijv** [Alex1911-Jiang/GreenOnions#8]
可以添加一个
自己往一个文件夹里塞图片，然后发指令，bot随机发一张
（？<数量>）(?<单位>）库（？<图集文件夹名字>）涩图，这样的
求你啦

**Comment by Alex1911-Jiang** [comment]
插件仓库 https://github.com/Alex1911-Jiang/GreenOnions.Plugins
