### ISSUE TITLE
老是出现这个错误

### ISSUE THREAD

**Issue by modeilan** [Alex1911-Jiang/GreenOnions#9]
我还以为我个个组件太老，但换了个新换件还是这样，求大佬看看linux环境的
![image](https://user-images.githubusercontent.com/106938600/183285190-9f018c4a-5402-40fe-902f-c7902571631a.png)

**Comment by Alex1911-Jiang** [comment]
有改过命令吗, 看起来像是正则错了, 没有的话看看目录下有没有config,json文件, 有就删掉它重新运行让它自己重新生成
没有的话, emmmm, 可以先用windows端生成一个配置文件拷过去

**Comment by modeilan** [comment]
> 有改过命令吗， 看起来像是正则错了， 没有的话看看目录下有没有config，json文件， 有就删掉它重新运行让它自己重新生成 没有的话， emmmm， 可以先用windows端生成一个配置文件拷过去

没改过，全新的都这样报错，有这个文件，我先试试第二个方法吧

**Comment by modeilan** [comment]
> 有改过命令吗， 看起来像是正则错了， 没有的话看看目录下有没有config，json文件， 有就删掉它重新运行让它自己重新生成 没有的话， emmmm， 可以先用windows端生成一个配置文件拷过去

两个方法都不得行，还是同样的错误，大佬的linux端会复现么

**Comment by Alex1911-Jiang** [comment]
我这暂时没有linux的机子, 你是一运行就报这个错吗?

**Comment by modeilan** [comment]
> 我这暂时没有linux的机子, 你是一运行就报这个错吗?

对一运行就报错。。

**Comment by Alex1911-Jiang** [comment]
我先装个WSL试试...

**Comment by modeilan** [comment]
> 我先装个WSL试试...

大佬加个qq1261593711细说下，实在不行我把服务器发你看看
